import { ThemeConfig } from '../types/resume';

export const THEMES: ThemeConfig[] = [
  {
    id: 'slate-pro',
    name: 'Slate Pro',
    headingColor: '#0f172a',
    bodyColor: '#334155',
    accentColor: '#3b82f6',
    backgroundAccent: '#f1f5f9',
    fontPairing: { heading: "'DM Sans', sans-serif", body: "'DM Sans', sans-serif" },
    densityScale: 1,
    borderStyle: 'solid',
    badgeStyle: 'rounded-md bg-blue-100 text-blue-800',
  },
  {
    id: 'emerald-exec',
    name: 'Emerald Executive',
    headingColor: '#064e3b',
    bodyColor: '#1f2937',
    accentColor: '#10b981',
    backgroundAccent: '#ecfdf5',
    fontPairing: { heading: "'Playfair Display', serif", body: "'Source Sans 3', sans-serif" },
    densityScale: 1,
    borderStyle: 'solid',
    badgeStyle: 'rounded-sm bg-emerald-100 text-emerald-800',
  },
  {
    id: 'crimson-edge',
    name: 'Crimson Edge',
    headingColor: '#1e1e1e',
    bodyColor: '#2d2d2d',
    accentColor: '#dc2626',
    backgroundAccent: '#fef2f2',
    fontPairing: { heading: "'Bebas Neue', sans-serif", body: "'IBM Plex Sans', sans-serif" },
    densityScale: 0.95,
    borderStyle: 'solid',
    badgeStyle: 'rounded-none bg-red-100 text-red-800 uppercase text-xs tracking-wider',
  },
  {
    id: 'midnight-tech',
    name: 'Midnight Tech',
    headingColor: '#a78bfa',
    bodyColor: '#e2e8f0',
    accentColor: '#818cf8',
    backgroundAccent: '#1e1b4b',
    fontPairing: { heading: "'Space Grotesk', monospace", body: "'JetBrains Mono', monospace" },
    densityScale: 0.9,
    borderStyle: 'dashed',
    badgeStyle: 'rounded bg-indigo-900 text-indigo-200 border border-indigo-700',
  },
  {
    id: 'gold-prestige',
    name: 'Gold Prestige',
    headingColor: '#78350f',
    bodyColor: '#292524',
    accentColor: '#d97706',
    backgroundAccent: '#fffbeb',
    fontPairing: { heading: "'Cormorant Garamond', serif", body: "'Libre Baskerville', serif" },
    densityScale: 1.05,
    borderStyle: 'solid',
    badgeStyle: 'rounded bg-amber-100 text-amber-900 border border-amber-300',
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    headingColor: '#0c4a6e',
    bodyColor: '#1e3a5f',
    accentColor: '#0ea5e9',
    backgroundAccent: '#e0f2fe',
    fontPairing: { heading: "'Nunito', sans-serif", body: "'Open Sans', sans-serif" },
    densityScale: 1,
    borderStyle: 'solid',
    badgeStyle: 'rounded-full bg-sky-100 text-sky-800',
  },
  {
    id: 'forest-minimal',
    name: 'Forest Minimal',
    headingColor: '#14532d',
    bodyColor: '#1c1917',
    accentColor: '#16a34a',
    backgroundAccent: '#f0fdf4',
    fontPairing: { heading: "'Josefin Sans', sans-serif", body: "'Lato', sans-serif" },
    densityScale: 1.1,
    borderStyle: 'solid',
    badgeStyle: 'rounded-full bg-green-100 text-green-800',
  },
  {
    id: 'rose-quartz',
    name: 'Rose Quartz',
    headingColor: '#881337',
    bodyColor: '#1f2937',
    accentColor: '#f43f5e',
    backgroundAccent: '#fff1f2',
    fontPairing: { heading: "'Raleway', sans-serif", body: "'Mulish', sans-serif" },
    densityScale: 1,
    borderStyle: 'solid',
    badgeStyle: 'rounded-full bg-rose-100 text-rose-800',
  },
  {
    id: 'graphite-mono',
    name: 'Graphite Mono',
    headingColor: '#111827',
    bodyColor: '#374151',
    accentColor: '#6b7280',
    backgroundAccent: '#f9fafb',
    fontPairing: { heading: "'IBM Plex Mono', monospace", body: "'IBM Plex Mono', monospace" },
    densityScale: 0.95,
    borderStyle: 'solid',
    badgeStyle: 'rounded-none bg-gray-200 text-gray-800',
  },
  {
    id: 'violet-modern',
    name: 'Violet Modern',
    headingColor: '#3b0764',
    bodyColor: '#1e1b4b',
    accentColor: '#7c3aed',
    backgroundAccent: '#faf5ff',
    fontPairing: { heading: "'Sora', sans-serif", body: "'Inter', sans-serif" },
    densityScale: 1,
    borderStyle: 'solid',
    badgeStyle: 'rounded-md bg-violet-100 text-violet-800',
  },
];

export const getTheme = (id: string): ThemeConfig =>
  THEMES.find((t) => t.id === id) || THEMES[0];
